# Generated by Django 4.0.2 on 2022-03-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1', models.CharField(max_length=80)),
                ('option2', models.CharField(max_length=80)),
                ('Analysis_op1', models.CharField(max_length=200)),
                ('Analysis_op2', models.CharField(max_length=200)),
            ],
        ),
    ]
