# Generated by Django 4.0.2 on 2022-03-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='qid',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
