# Generated by Django 4.0.2 on 2022-03-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_decision_maker'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision_maker',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='decision_maker',
            name='qid',
            field=models.IntegerField(default=0),
        ),
    ]
