# Generated by Django 4.0.2 on 2022-03-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_decision_maker_marks_decision_maker_qid'),
    ]

    operations = [
        migrations.CreateModel(
            name='calc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.CharField(max_length=8)),
                ('option', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='quesans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.CharField(max_length=8)),
                ('option', models.CharField(max_length=8)),
            ],
        ),
    ]
