# Generated by Django 4.0.2 on 2022-03-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_calc_quesans'),
    ]

    operations = [
        migrations.CreateModel(
            name='final',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.IntegerField()),
                ('option', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='calc',
        ),
        migrations.DeleteModel(
            name='quesans',
        ),
    ]
