# Generated by Django 4.0.2 on 2022-03-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_final_delete_calc_delete_quesans'),
    ]

    operations = [
        migrations.AddField(
            model_name='final',
            name='img',
            field=models.URLField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='final',
            name='option',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='final',
            name='qid',
            field=models.IntegerField(default=0),
        ),
    ]
