# Generated by Django 4.0.2 on 2022-03-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_final_img_alter_final_option_alter_final_qid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='decision_maker',
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='timepass',
            field=models.CharField(default=' ', max_length=80),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='name',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
