# Generated by Django 4.0.2 on 2022-03-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_delete_decision_maker_basicinfo_timepass_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='colour',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='Analysis_op1',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='Analysis_op2',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option2',
        ),
        migrations.AddField(
            model_name='questions',
            name='ans',
            field=models.CharField(default=' ', max_length=800),
        ),
        migrations.AddField(
            model_name='questions',
            name='op1',
            field=models.CharField(default=' ', max_length=800),
        ),
        migrations.AddField(
            model_name='questions',
            name='op2',
            field=models.CharField(default=' ', max_length=800),
        ),
        migrations.AddField(
            model_name='questions',
            name='op3',
            field=models.CharField(default=' ', max_length=800),
        ),
        migrations.AddField(
            model_name='questions',
            name='op4',
            field=models.CharField(default=' ', max_length=800),
        ),
        migrations.AddField(
            model_name='questions',
            name='ques',
            field=models.CharField(default=' ', max_length=800),
        ),
        migrations.AlterField(
            model_name='questions',
            name='qid',
            field=models.CharField(default=' ', max_length=800),
        ),
    ]
