# Generated by Django 4.0.2 on 2022-03-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_delete_colour_remove_questions_analysis_op1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='qid',
            field=models.IntegerField(),
        ),
    ]
