# Generated by Django 4.0.2 on 2022-03-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_alter_questions_qid'),
    ]

    operations = [
        migrations.CreateModel(
            name='res',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responce', models.CharField(max_length=80)),
            ],
        ),
    ]
